# Generated by Django 3.2.4 on 2021-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
