# Generated by Django 3.2.4 on 2021-06-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210603_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
